# Disable secret scanning for specific packages
block-list-secret-scan: []  

# Enable compact output for better readability
compact: true  

# Scan the current directory
directory:
- ./

# Downloading external Terraform modules
download-external-modules: true  

# Evaluate Terraform variables for better analysis
evaluate-variables: true  

# Store external modules in this path
external-modules-download-path: .external_modules  

# Scan using all available frameworks
framework:
- all

# No masking of results
mask: []  

# Suppress non-essential output
quiet: true  

# No specific file types for secret scanning
secrets-scan-file-type: []  

# Show the summary at the top of the report
summary-position: top  

# Exclude specific paths from scanning
skip-path:
- venv/  # Exclude virtual environment directory

skip-check:
- CKV_TF_1
- CKV_AZURE_224 # Ledger feature is currently not required for this template
- CKV_AZURE_229 # Zone redundancy  is currently not required for this template